version: '3.8'

services:
  web:
    build: .
    ports:
      - "20.151.234.53:6567:5000"
    volumes:
      - ./flaskapp:/app/flaskapp
      - ./data:/app/data  # Adicione volume para o banco de dados SQLite3
    environment:
      FLASK_ENV: development
      FLASK_APP: flaskapp/app.py

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
