version: '3.8'

services:
  web:
    build: .
    ports:
      - "20.151.234.53:6567:5000"
    volumes:
      - ./flaskapp:/app/flaskapp
    environment:
      FLASK_ENV: development
      FLASK_APP: flaskapp/app.py  # Adicione esta linha
    command: >
      sh -c "python init_db.py && flask run --host=0.0.0.0"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
